spring:
  application:
    name: subject
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080/realms/matalino-realm

server:
  port: 8081

logging:
  level:
    org.springframework: INFO
    com.yourpackage: DEBUG
