import React from "react";
import { lessonsContents, customLessons } from "../constants/contents";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";

function Lessons() {
  return (
    <section className="px-6 py-12 max-w-7xl mx-auto space-y-16">
      {/* Page Header */}
      <div className="max-w-4xl">
        <h1 className="text-3xl font-semibold text-gray-900">
          Learning pathways
        </h1>
        <p className="mt-2 text-gray-600">
          Explore curated pathways and AI-generated lessons tailored to your
          learning journey.
        </p>
      </div>

      {/* ================= DEFAULT PATHWAYS ================= */}
      <div className="space-y-8">
        <div>
          <h2 className="text-2xl font-semibold text-gray-900">
            Default pathways
          </h2>
          <p className="mt-1 text-gray-600">
            Curated learning paths covering essential topics and skills.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
          {lessonsContents.map((lesson, index) => (
            <div
              key={lesson.id ?? index}
              className="
                bg-white border border-gray-200 rounded-2xl
                p-6 flex flex-col
                hover:shadow-md transition-shadow
              "
            >
              <span className="text-xs font-semibold tracking-wide text-gray-500 uppercase">
                Pathway {index + 1}
              </span>

              <div className="flex justify-center my-6">
                <img
                  src={lesson.icon}
                  alt={lesson.name}
                  className="w-40 h-40 object-contain"
                />
              </div>

              <h3 className="text-xl font-semibold text-gray-900 mt-2">
                {lesson.name}
              </h3>

              <p className="text-sm text-gray-600 mt-2 flex-1">
                {lesson.description}
              </p>

              <Button
                variant="outline"
                className="mt-6 w-fit rounded-full px-6"
              >
                <Link to="/study" target="_blank">Explore</Link>
              </Button>
            </div>
          ))}
        </div>
      </div>

      {/* ================= CUSTOM (AI) LESSONS ================= */}
      <div className="space-y-8">
        <div>
          <h2 className="text-2xl font-semibold text-gray-900">
            Custom lessons
          </h2>
          <p className="mt-1 text-gray-600">
            Lessons generated by AI based on your goals and preferences.
          </p>
        </div>

        {customLessons.length === 0 ? (
          <p className="text-gray-500">
            No custom lessons yet. Generate one from the dashboard to see it
            here.
          </p>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {customLessons.map((lesson, index) => (
              <div
                key={lesson.id ?? index}
                className="
                  bg-white border border-gray-200 rounded-2xl
                  p-6 flex flex-col
                  hover:shadow-md transition-shadow
                "
              >
                {/* AI badge */}
                <span className="text-xs font-semibold uppercase text-indigo-600">
                  AI-generated
                </span>

                <h3 className="text-xl font-semibold text-gray-900 mt-4">
                  {lesson.name}
                </h3>

                <p className="text-sm text-gray-600 mt-2 flex-1">
                  {lesson.description}
                </p>

                <div className="flex items-center justify-between mt-6">
                  <span className="text-xs text-gray-400">
                    Generated {lesson.createdAt}
                  </span>

                  <Button
                    variant="outline"
                    className="rounded-full px-6"
                  >
                    Continue
                  </Button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </section>
  );
}

export default Lessons;
